version: '2.4'
services:
  obp-db:
    image: postgres:12.6
    container_name: obp
    restart: unless-stopped
    platform: linux
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: obp_db
      POSTGRES_USER: obp_user
      POSTGRES_PASSWORD: qwkabdtyybhu
    volumes:
      - c:\Data:/var/lib/postgresql
    
